version: 2

models:
  - name: daily_pressure_high_low
    description: "Determines high and low pressure reading for each day"
    
    columns:
      - name: date
        description: "the date of the reading"
        tests:
          - unique
          - not_null

      - name: high_pressure
        description: "highest pressure for the day"
        tests: 
          - not_null

      - name: low_pressure
        description: "lowest pressure for the day"
        tests: 
          - not_null